### PR TITLE
Put cq-server in a container

### PR DESCRIPTION
**Pull request by qwelyt**
Put the cq-server in a dockerimage so it can be run as a container.

### CODE REVIEW

**Comment by qwelyt** [comment]
This does the first part of #10

**Comment by roipoussiere** [comment]
Thanks for the PR.

Since 1b4acf2, when a directory is given as parameter, an index page is displayed from where the user can chose the Python script to render. So I think it's not necessary to add the `main.py` default script.

Also `data` folder is your work dir, so I think `"/data"` parameter is not required in the entry point (because `.` is the default dir).

Could you change that?

**Comment by qwelyt** [comment]
I'm having second thoughts about the removal of `/data` in the entrypoint.

If you do `docker run -v /some/path:/data cq-server` then that works great. But if you do `docker run -v /some/path:/data cq-server /some/other/path` then it fails to find anything as it looks for `/some/other/path` in the container. With having `/data` in the entrypoint it instead throws an error with `/some/other/path` being an unrecognized option.

So would you like it to throw an error, or cause the user to perhaps wonder why they can't find their modules?

**Comment by roipoussiere** [comment]
I think it's better to let entrypoint without `/data` and document the usage of the docker container, because it's important to let user define their own parameters.

Here is a use case:

    docker run -v /some/path:/data cq-server box.py --export

This is will fail if there is `/data` parameter in entrypoint.

**Pull request merged**
